---
# Web server configurator

- name: Fetch the (possibly empty) list of PHP socket files
  find:
    paths: /var/run/php
    patterns: "*.sock"
    file_type: any
  register: matomo_php_socket_files

- name: Set the PHP socket file
  set_fact:
    matomo_php_socket_file: "{{ matomo_php_socket_files.files | sort(attribute='ctime', reverse=True) | map(attribute='path') | list | first }}"
  when: matomo_php_socket_files.matched > 0

- name: Inject the Matomo site's Nginx configuration
  template:
    src: "{{ matomo_nginx_template_file }}"
    dest: "{{ matomo_web_config_dir['available'] }}/matomo.conf"
    owner: "root"
    group: "root"
    mode: "preserve"
    backup: yes
  become: true

- name: Enable the site
  file:
    src: "{{ matomo_web_config_file['regular'] }}"
    dest: "{{ matomo_web_config_file['link'] }}"
    state: link
  become: true
