---

- name: Fetch results of the number of tables in the Matomo database
  command: >
    mysql
    --user={{ matomo_db.user }}
    --password={{ matomo_db_password }}
    --host={{ matomo_db.host }}
    --skip-column-names {{ matomo_db.name }}
    --execute="SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = '{{ matomo_db.name }}'"
  register: matomo_db_tables
  check_mode: no
  changed_when: False
  delegate_to: localhost

- name: Determine if the Matomo database requires an import
  set_fact:
     matomo_db_import_required: "{{ matomo_db_tables.stdout == '0' }}"

# Follow https://matomo.org/faq/how-to/faq_191/ as native hashing results in inability to login.
- name: Hash Matomo's superuser administration password
  command: >
    php -r 'echo password_hash(md5("{{ matomo_superuser_password }}"), PASSWORD_DEFAULT) . "\n";'
  register: matomo_superuser_password_hashed
  when: matomo_db_import_required

- name: Copy database dump for importing into newly created DB
  template:
    src: "matomo.sql.j2"
    dest: "{{ matomo_path['temporary'] }}/matomo.ansible.sql"
    owner: "root"
    group: "root"
    mode: "400"
    force: yes
  when: matomo_db_import_required
  delegate_to: localhost

- name: Import dump file into newly created database
  mysql_db:
    name: "{{ matomo_db.name }}"
    state: import
    target: "{{ matomo_path['temporary'] }}/matomo.ansible.sql"
    login_host: "{{ matomo_db.host }}"
    login_user: "{{ matomo_db.user }}"
    login_password: "{{ matomo_db_password }}"
  when: matomo_db_import_required
  delegate_to: localhost
