---
# Debian package installer

# Originally from https://mackuba.eu/2019/02/02/setting-up-piwik/

- name: "Load the Matomo apt repository key"
  apt_key:
    id: "{{ matomo_debian_repository_key_id }}"
    url: "{{ matomo_debian_repository_key_url }}"
  become: true

- name: "Add the Matomo repository to apt"
  apt_repository: 'repo="deb {{ matomo_debian_repository_url }} piwik main"'
  become: true

- name: "Set automatic upgrades in debconf"
  debconf:
    name: matomo
    question: matomo/automatic-upgrade
    value: "{{ matomo_debian_automatic_upgrades }}"
    vtype: boolean
  become: true

- name: "Install Matomo apt package"
  apt:
    name: matomo=3.0.4-1
    state: present
    update_cache: yes
    cache_valid_time: 3600
    install_recommends: no
  become: true
  ignore_errors: true
  register: apt_install_result


- name: output apt result
  debug:
    var: apt_install_result
