---
# tasks file for ansible-role-matomo

- name: Configure the Web server
  import_tasks: configure-web-server.yml
  when: matomo_configure_web_server | bool

- name: Configure the application
  import_tasks: configure-application.yml

- name: replace pool config
  template:
    src: pool.conf.j2
    dest: /etc/php/7.2/fpm/pool.d/www.conf
    owner: root
    group: root
    mode: 0644

- name: Create the application's database
  import_tasks: create-database.yml

- name: Install the Debian package
  import_tasks: install-debian-package.yml

- name: Add additional functionality to the basic Matomo
  import_tasks: add-extras.yml
